-- ============================================================
-- K-Shop Full Backup – Generated 2026-04-29
-- Project: vtrzxykuhacrlqzgdbfe
-- Products: 209 | Contacts: 8 | Settings: 3
-- ============================================================

-- Schema (run this on fresh Supabase project)
-- ============================================================
-- K-Shop – Supabase Schema
-- הרץ את הקוד הזה בעורך ה-SQL של Supabase
-- ============================================================

-- ── 1. טבלת מוצרים ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS products (
  id             TEXT        PRIMARY KEY,
  name           TEXT        NOT NULL,
  category       TEXT,
  dimensions     TEXT,
  "costPrice"    NUMERIC     DEFAULT 0,
  warehouse      TEXT,
  quantity       INTEGER     DEFAULT 0,
  "futureQty"    INTEGER     DEFAULT 0,
  "futureDate"   TEXT,
  image          TEXT,
  sku            TEXT,
  display_order  INTEGER     DEFAULT 0,
  created_at     TIMESTAMPTZ DEFAULT NOW(),
  updated_at     TIMESTAMPTZ DEFAULT NOW()
);

-- ── 2. טבלת הגדרות (קטגוריות, מספר וואטסאפ וכו') ─────────────
CREATE TABLE IF NOT EXISTS app_settings (
  key    TEXT PRIMARY KEY,
  value  TEXT
);

-- ── 3. RLS – אפשר קריאה וכתיבה דרך anon key ──────────────────
ALTER TABLE products     ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;

-- מחק policies קיימות אם יש (כדי למנוע שגיאות כפל)
DROP POLICY IF EXISTS "anon_all_products"     ON products;
DROP POLICY IF EXISTS "anon_all_settings"     ON app_settings;

CREATE POLICY "anon_all_products"
  ON products
  FOR ALL
  TO anon
  USING (true)
  WITH CHECK (true);

CREATE POLICY "anon_all_settings"
  ON app_settings
  FOR ALL
  TO anon
  USING (true)
  WITH CHECK (true);

-- ── 4. Trigger לעדכון updated_at אוטומטי ─────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at ON products;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON products
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- Add warehouse_qty column if missing
ALTER TABLE products ADD COLUMN IF NOT EXISTS warehouse_qty TEXT;

-- Contacts table
CREATE TABLE IF NOT EXISTS contacts (
  id TEXT PRIMARY KEY,
  name TEXT,
  phone TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS contacts_all ON contacts;
CREATE POLICY contacts_all ON contacts FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ── Products (209 rows) ──────────────────────────────────────
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('1','מתנפח קרניבל 4 תחנות','carnival','אורך: 6 עומק: 2.4 גובה: 3.7','0','alishma_old',4,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-19-11.04.00.jpg','X096',0,'{"alishma_old": 2, "alishma_new": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('2','מתנפח קליעה למטרה כדורגל','sport','אורך:2.4 עומק: 2.1 גובה: 2.4','0','alishma_old',10,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/מתנפח-קליעה-למטרה.jpg','X301',1,'{"alishma_old":3,"alishma_new":7}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('3','שער כניסה לבת מצווה','arch','רוחב: 6 מ גובה: 4.8','0','alishma_old',3,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/שער-כניסה-לבת-מצווה.jpg',NULL,2,'{"alishma_old":3}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('4','מתנפח באולינג 2 מסלולים','sport','אורך: 5 רוחב: 3 גובה: 1.42','0','alishma_old',3,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/באולינג-ענק.jpg',NULL,3,'{"alishma_old":3}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('5','מתנפח WHACK A WALL','sport','אורך: 4 עומק: 1.5 גובה: 2.05','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-21-09.11.49.jpg',NULL,4,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('179','מתנפח 3 תחנות בסגנון קרקס','carnival','2.5x2x3.95m','0','alishma_old',4,0,'','https://k-shop.co.il/wp-content/uploads/2026/04/WhatsApp_Image_2026-04-14_at_11.07.35-removebg-preview-2.png',NULL,5,'{"alishma_old":4}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('7','10 תחנות לונה ספורט','carnival','כל ביתן זוגי: רוחב: 1.20 גובה: 2.10','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-21-09.16.49.jpg','X390',6,'{"alishma_old":1,"alishma_new":0}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('8','ביתני קליעה מתנפחים','carnival','כל ביתן: רוחב: 1.50 עומק: 2','0','alishma_new',3,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-21-09.11.09.jpg','X383',7,'{"alishma_new":2,"alishma_old":1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('9','מתנפח איקס עיגול משולב','carnival','אורך: 2.5 עומק: 1.8 גובה: 3.30','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-04-29-11.41.04.jpg','X045',8,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('10','מתנפח גרזנים Viking','carnival','4X4','0','alishma_old',3,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-04-29-11.47.09-removebg-preview.png','X101',9,'{"alishma_old":3}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('11','מתנפח קליעה Viking זוגי','carnival','','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/WhatsApp-Image-2022-08-22-at-17.52.20-1.jpeg',NULL,10,'{"alishma_old":1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('12','מתנפח שער כדורגל','sport','אורך: 4 עומק: 2 גובה: 2.5','0','alishma_new',3,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-19-11.05.42.jpg','X082',11,'{"alishma_new": 3}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('13','מתנפח ביליארד רגל','sport','אורך: 7.8 רוחב: 4.8 גובה: 0.45','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-19-18.27.52.jpg','X015',12,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('14','מתנפח כדורסל אנושי','sport','קוטר: 1.5 גובה: 3','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-12-13.26.53.jpg','X331',13,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('15','מתנפח קרניבל 3 תחנות','carnival','אורך: 5.8 עומק: 2.24 גובה: 2.87','0','alishma_new',1,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-19-18.21.44-removebg-preview.png','X300',14,'{"alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('16','מתנפח קרניבל 5 תחנות','carnival','קוטר: 4.5 גובה: 4','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-04-29-11.51.55-removebg-preview.png',NULL,15,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('17','מתנפח מתחם לגו ענק 5/5 ללא רצפה','gymboree','אורך: 5 רוחב: 5 גובה: 2.54','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-18-09.10.55.jpg',NULL,16,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('18','מתנפח דרבי סוסים','sport','אורך: 6 רוחב: 4.5 גובה: 2.85','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-21-09.12.23.jpg',NULL,17,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('19','מתנפח כדורסל SUPER STAR','sport','אורך: 4 עומק: 3.5 גובה: 3.35','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-21-09.13.09.jpg','X226',18,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('6','מתנפח פינגווין כדורים','carnival','אורך: 3.60 עומק: 1.50 גובה: 2.70','0','alishma_old',4,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/IMG_7901.jpg','X305',19,'{"alishma_old": 4}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('21','שער כניסה HAPPY BIRTHDAY','arch','רוחב: 2.5 מ גובה: 2.5 קוטר: 0.30','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-19-18.22.25.jpg',NULL,20,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('22','בובת דנסר 2 רגליים','arch','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-21-09.13.37.jpg',NULL,21,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('23','בובת דנסר','arch','','0','alishma_old',7,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-21-09.15.25.jpg','X228',22,'{"alishma_old": 3, "misrad": 4}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('24','מתנפח קליעה זומבי','carnival','רוחב: 2.40 עומק: 3 גובה: 2.75','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-21-09.16.44.jpg','X436',23,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('25','רשת כדור עף לבריכה','pool','רוחב:3 מטר גובה: 1 מטר','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2017-08-11-09.18.58.jpg',NULL,24,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('26','חליפות סומו מבוגר','sport','','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-21-09.18.17.jpg','X071',25,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('27','חליפות סומו ילדים','sport','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-21-09.18.26.jpg',NULL,26,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('28','מתנפח מסלול מכונית / קארטינג','sport','אורך: 12 עומק: 6','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/12/2021-12-05-10.05.51.jpg',NULL,27,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('29','מתנפח כדורגל SUPER TARGET','sport','אורך:4 עומק: 2.5 גובה: 3.6','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/12/2021-12-05-10.06.21.jpg',NULL,28,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('30','מתנפח כדורסל WINNER','sport','אורך: 4 עומק: 3 גובה: 2.5','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/12/2021-12-05-10.06.07.jpg',NULL,29,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('31','מתנפח קקטוס טבעות','carnival','אורך: 3 עומק: 1.5 גובה: 1.80','0','alishma_old',3,0,'','https://k-shop.co.il/wp-content/uploads/2021/12/2021-12-05-09.56.38.jpg','X308',30,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('32','מתנפח כדורגל אנושי','sport','אורך: 10 עומק: 5 גובה: 1.3','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/12/כדורגל-אנושי.jpg',NULL,31,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('33','מתנפח חץ וקשת כדורים','sport','אורך: 3 עומק: 2 גובה: 2.5','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2021/12/2021-12-05-09.54.37.jpg','X307',32,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('35','כדורי Bubbel Soccer מתנפחים','sport','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2022/01/Diam-1-5m-1-2m-Giant-Inflatable-Human-Bumper-Bubble-Soccer-Ball-Sumo-Suit-Blow-Up.jpg',NULL,33,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('36','מתנפח מיטת צעצועים חיות','bounce','אורך: 5 עומק: 4 גובה: 1.90','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2022/01/2021-12-05-10.05.29-scaled.jpg',NULL,34,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('37','מתנפח טירת קפיצות ג''ירפה','bounce','אורך: 4.5 עומק: 4.5 גובה: 4.56','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2022/01/2021-12-05-10.02.45.jpg','X314',35,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('38','מתנפח השחלת טבעות','carnival','אורך: 3 עומק: 1.5 גובה: 1.32','0','alishma_old',3,0,'','https://k-shop.co.il/wp-content/uploads/2022/04/IMG_3727-scaled.jpg','X334',36,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('20','מתנפח הכדורים המעופפים','carnival','אורך: 3 עומק: 1.48 גובה: 2.10','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-18-09.11.35.jpg',NULL,37,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('40','בריכה חד קרן עם שסתום','pool','אורך: 5 רוחב: 4 גובה: 0.50 גובה סופי: 2.10','0','alishma_old',4,0,'','https://k-shop.co.il/wp-content/uploads/2022/04/2021-12-05-09.56.05-scaled.jpg',NULL,38,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('41','בריכת חד קרן','pool','אורך: 5 רוחב: 4 גובה: 0.50 גובה סופי: 2.10','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2022/04/2021-12-05-09.56.05-scaled.jpg',NULL,39,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('42','בריכת מים 4/4','pool','אורך: 4 רוחב: 4 גובה: 0.48','0','alishma_old',3,0,'','https://k-shop.co.il/wp-content/uploads/2022/04/בריכה-5-5-scaled.jpg',NULL,40,'{"alishma_old":3}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('84','בריכת מים 5/5','pool','אורך: 5 רוחב: 5 גובה: 0.48','0','alishma_old',8,0,'','https://k-shop.co.il/wp-content/uploads/2022/04/בריכה-5-5-scaled.jpg','X335',41,'{"alishma_old":8}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('43','בריכת מים 6/6','pool','אורך: 6 רוחב: 6 גובה: 0.48','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2022/04/בריכה-5-5-scaled.jpg',NULL,42,'{"alishma_old":2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('45','מתנפח טירת קפיצות חד קרן','bounce','אורך: 4.5 עומק: 4.5 גובה: 5.10','0','alishma_old',1,2,'2026-04-29','https://k-shop.co.il/wp-content/uploads/2022/06/טירת-קפיצות-חד-קרן.jpg','KS-001U',43,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('83','בריכת מים 7/7','pool','אורך: 7 רוחב: 7 גובה: 0.48','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2022/04/בריכה-8-8-1-scaled.jpg',NULL,44,'{"alishma_old":1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('47','בריכת כדורים דינוזאורים','gymboree','','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2022/07/WhatsApp-Image-2022-07-28-at-17.13.54.jpeg',NULL,45,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('48','בריכת כדורים קרקס','gymboree','','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2022/07/WhatsApp-Image-2022-07-28-at-17.13.54-1.jpeg','X325',46,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('49','מגרש כדורגל / כדורעף / כדורסל משולב','sport','אורך:12 מטר רוחב: 6 מטר גובה: 3 מטר','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2022/07/WhatsApp-Image-2022-07-31-at-10.09.07.jpeg',NULL,47,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('50','מתנפח כדורסל 4 בשורה','sport','אורך:2.74 מטר עומק: 3.66 מטר גובה: 3.66 מטר','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2022/07/WhatsApp-Image-2022-07-31-at-10.24.49.jpeg','X368',48,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('51','מתנפח תא דולרים','sport','רוחב: 1.80 גובה 2.50','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2022/08/WhatsApp-Image-2022-08-22-at-17.53.14.jpeg','X310',49,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('52','תחנות משחק מתנפחות קונספט ספארי','carnival','כל ביתן: רוחב: 1.50 עומק: 2 גובה:2.60','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2022/09/ספארי-1.jpeg',NULL,50,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('53','מתנפח כדורגל גול הזהב','sport','אורך: 3.5 עומק: 3.5 גובה: 2.5','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2022/09/גול-הזהב-01.jpeg',NULL,51,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('54','מתנפח לימבו','sport','אורך: 3.5 עומק: 1.5 גובה: 3.4','0','alishma_new',1,0,'','https://k-shop.co.il/wp-content/uploads/2022/09/לימבו-2.jpeg','X332',52,'{"alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('55','מתנפח מבוך 8/8','sport','אורך: 8 עומק: 8 גובה: 2.16','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2022/09/מבוך-מתנפח-5.jpeg',NULL,53,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('56','מתנפח ויקינג זוגי Hammer','carnival','','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2022/10/WhatsApp-Image-2022-10-20-at-16.50.50.jpeg','X444',54,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('57','מתנפח קרניבל 2 תחנות','carnival','אורך: 3 עומק: 2.4 גובה: 3.4','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2022/10/WhatsApp-Image-2022-10-26-at-19.24.02-1-removebg-preview.png','X320',55,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('39','מתנפח כדורים מרחפים','carnival','אורך: 5 עומק: 1.92 גובה: 1.68','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2022/04/2022-04-03-10.17.30.jpg',NULL,56,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('59','מתנפח מתחם לגו ענק 4/4 ללא רצפה','gymboree','אורך: 4 רוחב: 4 גובה: 2.54','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-18-09.10.55.jpg',NULL,57,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('60','מתנפח מתחם לגו ענק 3/4 ללא רצפה','gymboree','אורך: 4 רוחב: 3 גובה: 2.54','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2022/10/2022-10-29-12.17.32-scaled.jpg',NULL,58,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('61','מתנפח מתחם לגו ענק 3/4 כולל רצפה','gymboree','אורך: 4 רוחב: 3 גובה: 2.54','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2022/10/2022-10-29-12.17.03-scaled.jpg',NULL,59,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('62','מתנפח מתחם לגו ענק 4/4 כולל רצפה','gymboree','אורך: 4 רוחב: 4 גובה: 2.54','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2022/10/2022-10-29-12.19.27-scaled.jpg','A24',60,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('63','מתנפח מתחם לגו ענק 6/4 לא כולל רצפה','gymboree','אורך: 6 רוחב: 4 גובה: 2.54','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2022/10/2022-10-29-12.19.08-scaled.jpg','A24',61,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('64','מתנפח ספורט משולב','sport','אורך: 3.90 עומק: 3 גובה: 3.90','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2022/10/WhatsApp-Image-2022-10-29-at-21.40.56.jpeg','X333',62,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('65','מתנפח מסלול מכונית / קארטינג RIDERS','sport','אורך: 12 עומק: 6','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2022/11/2022-04-28-00.25.31.jpg',NULL,63,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('66','מתנפח כדורגל סטנגה משולב כדורסל 6 משתתפים','sport','פנימי 6 קוטר','0','alishma_old',3,0,'','https://k-shop.co.il/wp-content/uploads/2022/12/WhatsApp-Image-2022-12-27-at-17.26.27-1-1.jpeg','X393',64,'{"alishma_old": 3}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('67','שער כניסה מתנפח','arch','אורך: 6 מטר','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2022/12/WhatsApp-Image-2022-12-28-at-08.54.15.jpeg','X394',65,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('68','מתנפח כדורסל 8 סלים Multiplayer','sport','','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2023/01/WhatsApp_Image_2024-01-02_at_11.13.01-removebg-preview.png','X397',66,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('69','מתנפח אתגרון SAFARI משולב מגלשה','challenge','אורך: 9 מטר','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2023/01/WhatsApp-Image-2023-01-04-at-16.42.09.jpeg',NULL,67,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('70','מגלשת מים VOLCANO','waterslide','אורך: 7 מטר  רוחב: 3 מטר  גובה: 4.50 מטר  גובה גלישה: 2 מטר','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2023/01/מגלשת-מים.jpg','KS-107-1',68,'{"alishma_old":2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('72','מתנפח כדורסל 3 סלים','sport','רוחב: 4 עומק: 3 גובה: 4','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2022/10/WhatsApp-Image-2023-01-31-at-12.33.06.jpeg','X336',69,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('73','מתנפח כדורסל 2 סלים','sport','רוחב: 3 עומק: 4 גובה: 4.20','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2023/02/WhatsApp-Image-2023-01-31-at-12.34.33.jpeg',NULL,70,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('74','מתנפח מגלשת ליצן','challenge','אורך: 6 מטר','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2023/03/מגלשת-ליצן-2.jpeg','X395',71,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('75','מתנפח קפיצות ספארי משולב מגלשה','bounce','רוחב: 5 עומק: 4 גובה: 3.3','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2023/03/WhatsApp_Image_2023-03-16_at_10.12.06-removebg-preview.png',NULL,72,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('76','שער כניסה מעוצב קשת בענן','arch','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2023/03/שער-קשת-בענן-1.jpg',NULL,73,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('77','מתנפח הישרדות ל-4 משתתפים','sport','רוחב: 6.5 עומק: 6.5 גובה: 4','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2023/05/WhatsApp_Image_2023-05-07_at_13.51.41-removebg-preview.png',NULL,74,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('78','מתנפח הפל אותי','sport','','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2023/05/WhatsApp_Image_2023-05-07_at_13.53.00__1_-removebg-preview.png','X485',75,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('80','מתנפח אתגרון פיראטים משולב מגלשה','challenge','אורך: 7 מטר','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2023/05/WhatsApp_Image_2023-05-14_at_11.35.20-removebg-preview-1.png',NULL,76,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('81','מתנפח קרניבל 4 תחנות בסגנון קומיקס','carnival','אורך: 6 עומק: 2.4 גובה: 3.7','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2023/05/WhatsApp_Image_2023-05-23_at_16.35.48-removebg-preview.png',NULL,77,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('82','מתנפח מתחם לגו ענק 5/4 כולל רצפה','gymboree','אורך: 5 רוחב: 4 גובה: 2.54','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-18-09.10.55.jpg','A24',78,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('44','בריכת מים 8/8','pool','אורך: 8 רוחב: 8 גובה: 0.48','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2022/04/בריכה-8-8-1-scaled.jpg',NULL,79,'{"alishma_old":1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('46','מגרש כדורעף צף לבריכה','pool','','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2022/07/WhatsApp-Image-2022-07-27-at-13.07.24.jpeg','X369',80,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('85','מתנפח ג׳ימבורי ממתקים 5/5 כולל רצפה','gymboree','אורך: 5 רוחב: 5','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2023/10/WhatsApp-Image-2023-10-16-at-06.57.20.jpeg','X364',81,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('86','מתנפח ג׳ימבורי דינוזאורים 5/5 כולל רצפה','gymboree','אורך: 5 רוחב: 5','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2023/10/WhatsApp-Image-2023-10-16-at-06.59.09-2.jpeg','X364',82,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('87','מתנפח בייסבול','sport','אורך: 3 גובה: 3.5','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2023/10/WhatsApp-Image-2023-10-16-at-06.59.47-1.jpeg','X405',83,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('88','סט 4 תחנות משחק','carnival','כל ביתן: רוחב: 1.50 עומק: 2 גובה:2.60','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2023/10/WhatsApp-Image-2023-10-16-at-07.02.23.jpeg','X403',84,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('89','מתנפח חנות ממתקים','arch','רוחב: 4 גובה 2.65 עומק 1.30','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2023/10/WhatsApp-Image-2023-10-16-at-07.19.34-1.jpeg','X407',85,'{"alishma_old": 1, "alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('90','מתנפח מסלול באולינג','sport','אורך: 5 רוחב: 1.8 גובה: 1.42','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2023/10/WhatsApp_Image_2023-10-26_at_12.22.49-removebg-preview.png','X119',86,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('91','מתנפח מולטי 6 תחנות ספורט','sport','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/01/WhatsApp-Image-2023-12-28-at-16.55.29.jpeg',NULL,87,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('92','מתנפח מגלשת ממתקים','bounce','','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2024/01/WhatsApp_Image_2024-01-22_at_13.58.48-removebg-preview.png','X328',88,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('93','מתנפח קרניבל 4 תחנות בסגנון ממתקים','carnival','אורך: 6 עומק: 2.4 גובה: 3.7','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/02/מתנפח-יריד-3.jpg',NULL,89,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('94','מתנפח קפיצות קרקס משולב מגלשה','bounce','רוחב: 5 עומק: 4 גובה: 3.3','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2024/02/WhatsApp_Image_2024-02-08_at_17.18.48-removebg-preview.jpg',NULL,90,'{"alishma_new":1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('95','מתנפחי הסוואה ללייזר קווסט','sport','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/02/WhatsApp_Image_2024-02-11_at_18.45.47-removebg-preview-1.png',NULL,91,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('96','מסך הקרנה 6/4','arch','','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2024/02/WhatsApp_Image_2024-02-13_at_08.58.11-removebg-preview.png','X404',92,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('97','מתנפח מתחם לגו ענק 5/5 כולל רצפה','gymboree','אורך: 5 רוחב: 5 גובה: 2.54','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2021/07/2021-06-18-09.10.55.jpg',NULL,93,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('126','מגלשת מים קרנבל','waterslide','גובה: 5.80 גובה גלישה: 3.00 מטר אורך: 8 מטר רוחב: 3 מטר','0','alishma_new',2,0,'','https://k-shop.co.il/wp-content/uploads/2024/12/WhatsApp_Image_2024-12-12_at_18.36.00__17_-removebg-preview-1-1.png','X436-C',94,'{"alishma_new":2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('99','מתנפח כדורגל מים','sport','אורך: 10 מטר','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/04/WhatsApp-Image-2024-04-18-at-09.04.26.jpeg',NULL,95,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('100','מתנפח קרניבל 3 תחנות קרקס','carnival','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/05/WhatsApp_Image_2024-04-30_at_09.18.25__3_-removebg-preview.png',NULL,96,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('101','מתנפח קרניבל Candy','carnival','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/05/WhatsApp_Image_2024-04-30_at_09.24.56-removebg-preview.png',NULL,97,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('102','מתנפח מתחם לגו ענק 6/4 כולל רצפה','gymboree','אורך: 6 רוחב: 4 גובה: 2.54','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2022/10/2022-10-29-12.19.08-scaled.jpg',NULL,98,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('103','מתנפח מפלצות טבעות','carnival','אורך: 3 עומק: 1.5 גובה: 1.80','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2024/05/WhatsApp_Image_2024-05-05_at_09.43.50-removebg-preview-1.png','X406',99,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('104','מתנפח קפיצות גלגל ענק','bounce','אורך 4.5 רוחב 4.5 גובה 4','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2024/05/WhatsApp_Image_2024-05-01_at_09.03.53-removebg-preview.png','X306',100,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('105','בובת ליצן מתנפחת פסים','character','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/07/ליצן-פסים.jpg',NULL,101,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('106','בובת ליצן מתנפחת משבצות','character','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/07/בובות-ליצן-מתנפחת.jpg',NULL,102,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('107','בובת ליצן הפוך מתנפחת סגול','character','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/07/בובה-מתנפחת-ליצן-הפוך.jpg',NULL,103,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('108','בובת ליצן הפוך מתנפחת אדום','character','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/07/בובה-מתנפחת-ליצן-הפוך-אדום.jpg',NULL,104,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('109','שער כניסה ממתקים (4 מטר) / CANDY','arch','','0','alishma_new',1,0,'','https://k-shop.co.il/wp-content/uploads/2024/07/שער-כניסה-ממתקים-1.jpg','X507',105,'{"alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('110','שער כניסה ממתקים (5 מטר) / CANDY','arch','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/07/שער-כניסה-ממתקים-1.jpg',NULL,106,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('111','מתנפח Golden Ticket קרקס','carnival','','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2024/07/WhatsApp_Image_2024-07-02_at_18.24.31__4_-removebg-preview.png','X429',107,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('112','מגלשת מים דיסקו','waterslide','גובה: 5.80 גובה גלישה: 3.00 מטר אורך: 8 מטר רוחב: 3 מטר','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2024/07/WhatsApp_Image_2024-07-28_at_12.45.38-removebg-preview.png',NULL,108,'{"alishma_old":2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('138','מגלשת מים חלל','waterslide','גובה: 5.80 גובה גלישה: 3.00 מטר אורך: 8 מטר רוחב: 3 מטר','0','alishma_new',1,0,'','https://k-shop.co.il/wp-content/uploads/2025/03/WhatsApp_Image_2025-03-04_at_21.07.05-removebg-preview.png','X436-S',109,'{"alishma_old":0,"alishma_new":1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('158','מגלשת מים טראמפ בסגנון אמריקאי','waterslide','גובה: 5.80 גובה גלישה: 3.00 מטר אורך: 8 מטר רוחב: 3 מטר','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2025/12/WhatsApp_Image_2025-12-16_at_09.16.23__5_-removebg-preview.png','X436-U',110,'{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('115','מתנפח חוות סוסים כולל 4 סוסי פוני על גלגלים','gymboree','סוס M:','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2024/09/WhatsApp_Image_2024-09-03_at_18.22.35-removebg-preview.png','X431',111,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('116','מתנפח מבוך ענק (10/20)','sport','אורך: 20 עומק: 10','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/10/ללא-שם.png',NULL,112,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('117','מתנפח כדורסל SHOOT','sport','3/1.5','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/10/WhatsApp_Image_2024-10-29_at_15.23.58-removebg-preview.png',NULL,113,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('118','מתנפח זריקת פריסבי','sport','3/1.5','0','alishma_new',3,0,'','https://k-shop.co.il/wp-content/uploads/2024/10/WhatsApp_Image_2024-10-29_at_14.36.45__1_-removebg-preview.png','X439',114,'{"alishma_new": 3}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('119','מתנפח טירת קפיצות צבוענית','bounce','אורך: 4 עומק: 4 גובה: 4','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/10/WhatsApp_Image_2024-09-11_at_16.34.11-removebg-preview.png',NULL,115,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('58','מתנפח אוהל קרקס 5 תחנות','carnival','קוטר: 6 גובה: 5.75','0','alishma_old',3,0,'','https://k-shop.co.il/wp-content/uploads/2022/10/2022-04-14-09.45.22-removebg-preview.png','X388',116,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('121','מתנפח יריד 360 בסגנון קרקס','carnival','קוטר: 5 מטר','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/12/WhatsApp_Image_2024-12-16_at_18.44.18-removebg-preview.png','X463',117,'{"alishma_old":0}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('122','מתנפח עמדת DJ Full Moon','arch','רוחב: גובה:','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/12/WhatsApp_Image_2024-12-17_at_09.33.45-removebg-preview.png',NULL,118,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('123','מתנפח ויקינג זוגי צבעוני','carnival','','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2024/12/WhatsApp_Image_2024-12-12_at_18.36.00__4_-removebg-preview.png','X444',119,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('124','מתנפח שער כדורגל ממתקים','sport','אורך: 4 עומק: 2 גובה: 2.5','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/12/WhatsApp_Image_2024-12-12_at_18.36.00__8_-removebg-preview.png',NULL,120,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('125','מתנפח קליעה למטרה כדורגל ממתקים','sport','אורך:2.4 עומק: 2.1 גובה: 2.4','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2024/12/WhatsApp_Image_2024-12-12_at_18.36.35-removebg-preview.png','X450',121,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('142','מגלשת מים גלידות','waterslide','גובה: 5.80 גובה גלישה: 3.00 מטר אורך: 8 מטר רוחב: 3 מטר','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2025/05/WhatsApp_Image_2025-05-05_at_18.51.17__1_-removebg-preview.png',NULL,122,'{"alishma_old":2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('127','מתנפח חדר דיסקו','bounce','3.7X3.5','0','alishma_old',5,0,'','https://k-shop.co.il/wp-content/uploads/2024/12/WhatsApp_Image_2024-12-12_at_18.36.00__1_-removebg-preview.png','X443',123,'{"alishma_old": 5}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('128','מבוך לייזר קווסט 8/8','sport','אורך: 8 עומק: 8','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2024/12/WhatsApp-Image-2024-12-17-at-16.00.43-1.jpeg',NULL,124,'{"alishma_old":1,"alishma_new":1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('129','מתנפח מיטת צעצועים חלל','bounce','אורך: 5 עומק: 4 גובה: 1.90','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2024/12/WhatsApp_Image_2024-12-22_at_10.53.00-removebg-preview-2.png','KS-114',125,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('130','מתנפח טירת קפיצות חלל','bounce','אורך: 4.5 עומק: 4.5 גובה: 4','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/12/WhatsApp_Image_2024-12-22_at_12.09.32-removebg-preview-1.png',NULL,126,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('131','מתנפח בועה','gymboree','','0','alishma_old',3,0,'','https://k-shop.co.il/wp-content/uploads/2024/12/WhatsApp_Image_2024-12-25_at_20.46.52-removebg-preview.png','X467',127,'{"alishma_old": 1, "alishma_new": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('132','מתנפח קליעה רוגטקה','carnival','רוחב: 1.80 עומק: 2.50 גובה: 2.90','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2025/01/WhatsApp_Image_2025-01-21_at_10.30.43__3_-removebg-preview.png',NULL,128,'{"alishma_new":1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('120','מתנפח קרניבל 3 תחנות צבעוני','carnival','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2024/10/WhatsApp_Image_2024-10-31_at_12.39.07-removebg-preview-1-e1735043820426-4.png',NULL,129,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('134','מתנפח שער כדורגל צבעוני','sport','אורך: 4 עומק: 2 גובה: 2.5','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/02/WhatsApp_Image_2025-02-25_at_12.32.49-removebg-preview.png',NULL,130,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('135','תחנות משחק מתנפחות קונספט פיראטיים','carnival','כל ביתן: רוחב: 1.50 עומק: 2 גובה:2.60','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/02/WhatsApp-Image-2025-02-25-at-15.36.30-1.jpeg',NULL,131,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('136','מתנפח בול פגיעה בסגנון חלל','carnival','אורך 4.6 רוחב 3','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2025/03/WhatsApp_Image_2025-03-13_at_11.21.20-removebg-preview.png','X474',132,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('156','מגלשת מים כריש ענקית','waterslide','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/12/WhatsApp_Image_2025-12-15_at_08.06.35-removebg-preview.png',NULL,133,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('137','מגלשת מים צבעונית','waterslide','אורך: 7 מטר רוחב: 2.30  גובה: 3.6 גובה גלישה 2 מטר   ','0','alishma_old',3,0,'','https://k-shop.co.il/wp-content/uploads/2025/03/WhatsApp_Image_2025-03-23_at_10.05.01-removebg-preview.png',NULL,134,'{"alishma_old":3}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('139','מתנפח נינג''ה 19 מטר','challenge','אורך 19 מטר','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/04/WhatsApp_Image_2025-04-01_at_18.02.48__3_-removebg-preview.png',NULL,135,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('140','מתנפח שער קרנבל (4/2)','arch','4 על 2','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/04/WhatsApp_Image_2025-04-25_at_15.44.58-removebg-preview.png',NULL,136,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('141','מתנפח מתחם לייזר קווסט (10/6)','sport','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/05/WhatsApp_Image_2025-05-05_at_17.26.57__1_-removebg-preview.png',NULL,137,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('98','מגלשת מים דולפין','waterslide','אורך: 7 מטר רוחב: 2.30  גובה: 3.6 גובה גלישה 2 מטר   ','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2024/02/WhatsApp_Image_2024-02-25_at_13.33.46-removebg-preview-1.png','X402',138,'{"alishma_old":0,"alishma_new":1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('143','מתנפח קפיצות מכונית שטח','bounce','אורך: 4.5 עומק: 4.5 גובה: 4.56','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/05/WhatsApp_Image_2025-05-06_at_15.19.14__1_-removebg-preview-1.png',NULL,139,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('114','מגלשת מים פיראטיים','waterslide','אורך: 7 מטר רוחב: 2.30  גובה: 3.6 גובה גלישה 2 מטר   ','0','alishma_new',2,0,'','https://k-shop.co.il/wp-content/uploads/2024/07/WhatsApp_Image_2024-07-29_at_15.29.42-removebg-preview.png','X402P',140,'{"alishma_new":1,"alishma_old":1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('145','מתנפח שער חלל (4/2)','arch','4 על 2','0','alishma_new',1,0,'','https://k-shop.co.il/wp-content/uploads/2025/06/WhatsApp_Image_2025-06-18_at_20.29.04-removebg-preview.png','X480',141,'{"alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('146','מתנפח שער ספארי (4/2)','arch','4 על 2','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2025/06/WhatsApp_Image_2025-06-18_at_20.29.04__1_-removebg-preview.png','X479',142,'{"alishma_old": 1, "alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('147','מתנפח כדורסל זוגי','sport','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/06/WhatsApp_Image_2025-06-26_at_09.28.05-removebg-preview.png',NULL,143,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('148','תחנות משחק מתנפחות קונספט יריד','carnival','כל ביתן: רוחב: 1.50 עומק: 2 גובה:2.60','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/07/509427935_10162769968048516_8276776842030008919_n.jpg',NULL,144,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('149','מתנפח בול פגיעה','carnival','4X3X2.8','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/07/WhatsApp-Image-2025-07-24-at-15.42.49.jpeg',NULL,145,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('155','מגלשת מים דיסקו מיני','waterslide','אורך: 7 מטר רוחב: 2.30  גובה: 3.6 גובה גלישה 2 מטר   ','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/09/WhatsApp-Image-2025-09-04-at-11.12.34-scaled.jpeg',NULL,146,'{"alishma_old":0}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('151','מתנפח עיר הילדים משולב','bounce','','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2025/08/WhatsApp_Image_2025-08-17_at_10.15.31-removebg-preview.jpg','KS-250',147,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('152','מתנפח רשת כדורעף','sport','','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2025/08/WhatsApp-Image-2025-08-10-at-18.06.40-2.jpeg','X495',148,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('153','מתנפח טירת קפיצות אדומה','bounce','אורך: 2.8 עומק: 2.8 גובה: 2.5','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2025/08/ChatGPT-Image-Aug-20-2025-06_07_14-PM.png','KS-001',149,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('154','מתנפח אתגרון ספינת השודדים משולב מגלשה','challenge','אורך: 8 מטר','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/09/ללא-שם.png',NULL,150,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('150','מגלשת מים רובוט','waterslide','אורך: 7 מטר רוחב: 2.30  גובה: 3.6 גובה גלישה 2 מטר   ','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/08/WhatsApp_Image_2025-08-07_at_17.39.54-removebg-preview.png',NULL,151,'{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('113','מגלשת מים ממתקים','waterslide','אורך: 7 מטר רוחב: 2.30  גובה: 3.6 גובה גלישה 2 מטר   ','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2024/07/WhatsApp_Image_2024-07-29_at_09.46.06__5_-removebg-preview-1.png',NULL,152,'{"alishma_old":1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('157','סירת פדלים לילדים – סירת מים צבעונית עם פדלים','pool','','0','alishma_old',8,0,'','https://k-shop.co.il/wp-content/uploads/2025/12/WhatsApp_Image_2025-07-17_at_17.57.19__1_-removebg-preview.png','X489',153,'{"alishma_old": 8}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('144','מתנפח שטיפת מכוניות (9/2.5)','waterslide','אורך: 9 רוחב: 2.5','0','alishma_old',2,0,'','https://k-shop.co.il/wp-content/uploads/2025/05/WhatsApp_Image_2025-05-14_at_11.28.55-removebg-preview.png',NULL,154,'{"alishma_old":2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('159','מגלשת מים טראמפ ענקית 15 מטר','waterslide','אורך: 15 מטר','0','alishma_new',2,0,'','https://k-shop.co.il/wp-content/uploads/2025/12/WhatsApp_Image_2025-12-23_at_11.49.42-removebg-preview-1.png','X483',155,'{"alishma_new":2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('160','מתנפח קפיצה דיסקו ענק','bounce','אורך 6 מטר | רוחב 4.8 מטר','0','alishma_old',5,0,'','https://k-shop.co.il/wp-content/uploads/2025/12/WhatsApp_Image_2025-12-25_at_15.47.39-removebg-preview-1.png','X470',156,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('161','מתנפח עמדת DJ אוזניות','arch','','0','alishma_new',2,0,'','https://k-shop.co.il/wp-content/uploads/2025/12/WhatsApp_Image_2025-12-30_at_13.20.56-removebg-preview.png','X501',157,'{"alishma_new": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('162','מתנפח ARENA – זירת משחק אינטראקטיבית למערכת IPS','sport','','0','alishma_new',2,0,'','https://k-shop.co.il/wp-content/uploads/2025/12/WhatsApp_Image_2025-12-30_at_17.37.22__1_-removebg-preview.png','X503-1',158,'{"alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('163','מייצג מתנפח אריה ענק','character','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-12-at-17.33.33-1-2.jpeg',NULL,159,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('164','מייצג מתנפח זברה ענק','character','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2026/01/מייצג-זברה.jpeg',NULL,160,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('165','מייצג מתנפח ג''ירפה ענק','character','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2026/01/מייצב-מתנפח-גירפה.jpeg',NULL,161,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('166','מייצג מתנפח תוכי ענק','character','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-12-at-17.33.32-1-1.jpeg',NULL,162,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('167','מייצג מתנפח טוטם טיקי ענק','character','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-12-at-17.33.32.jpeg',NULL,163,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('168','מייצג מתנפח פיל ענק','character','','0','alishma_new',2,0,'','https://k-shop.co.il/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-12-at-18.29.42-1.jpeg','X508',164,'{"alishma_new": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('169','שער כניסה מתנפח גיבורים','arch','','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-15-at-11.48.48-1.jpeg',NULL,165,'{"alishma_old":0}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('170','שער כניסה מתנפח ממתקים','arch','רוחב: 4.5 מטר  גובה: 3.3 מטר  רוחב מעבר כניסה: 2.3 מטר','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-15-at-09.16.27-1.jpeg',NULL,166,'{"alishma_old":1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('171','שער כניסה מתנפח סוכריות','arch','רוחב כללי: 4.5 מטר  גובה: 3.4 מטר  רוחב כניסה: 2 מטר','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-15-at-11.48.48-3-1.jpeg','X509',167,'{"alishma_new":0,"alishma_old":1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('172','בריכת מים K-Summer Pool 4/4','pool','4×4 מטר גובה: 0.48 ','0','alishma_old',5,0,'','https://k-shop.co.il/wp-content/uploads/2026/01/WhatsApp_Image_2026-01-27_at_09.52.29__1_-removebg-preview.png',NULL,168,'{"alishma_old":5}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('173','בריכת מים K-Summer Pool 5/5','pool','5x5 מטר גובה: 0.48','0','alishma_old',3,0,'','https://k-shop.co.il/wp-content/uploads/2026/01/WhatsApp_Image_2026-01-27_at_09.52.29__1_-removebg-preview.png',NULL,169,'{"alishma_old":3}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('174','בריכת מים K-Summer Pool 6/6','pool','6x6 מטר גובה: 0.48','0','alishma_old',3,0,'','https://k-shop.co.il/wp-content/uploads/2026/01/WhatsApp_Image_2026-01-27_at_09.52.29__1_-removebg-preview.png',NULL,170,'{"alishma_old":3}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('175','מתנפח קרניבל 3 תחנות חלל','carnival','','0','alishma_old',1,0,'','https://k-shop.co.il/wp-content/uploads/2026/01/WhatsApp_Image_2026-01-28_at_14.55.40-removebg-preview-1.png','X432',171,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('176','מתנפח הוקי אנושי בסגנון חלל','sport','8X3 מטר','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2026/02/WhatsApp-Image-2026-02-17-at-12.07.52-1.jpeg',NULL,172,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('177','מתנפח אתגרון בסגנון קרקס','challenge','8x3 מטר','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2026/02/WhatsApp_Image_2026-02-26_at_12.23.12-removebg-preview.png',NULL,173,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('178','מגלשת מים דולפין – דגם SPLASH PRO','waterslide','אורך: 5 רוחב: 2 מטר גובה כללי: 4.23 מטר גובה גלישה: 1.20 מטר','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2026/03/WhatsApp-Image-2026-03-02-at-13.13.24-1.jpeg',NULL,174,'{}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('133','מתנפח צבעוני טבעות','carnival','אורך: 3 עומק: 1.5 גובה: 1.80','0','alishma_old',0,0,'','https://k-shop.co.il/wp-content/uploads/2025/02/WhatsApp_Image_2025-02-11_at_13.55.10__1_-removebg-preview.png',NULL,175,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('200','מתנפח השחלת טבעות דינוזאורים','ללא קטגוריה',NULL,'0','alishma_old',2,0,NULL,NULL,'X308',176,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('201','מתנפח השחלת טבעות גלידות','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X308',177,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('202','מתנפח השחלת טבעות ליצנים','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X308',178,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('203','מתנפח השחלת טבעות פיראטים','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X469',179,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('204','מתנפח שער כדורגל לגו','ללא קטגוריה',NULL,'0','alishma_old',2,0,NULL,NULL,'X452',180,'{"alishma_old": 1, "alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('205','מתנפח פוטבול יחיד','ללא קטגוריה',NULL,'0','alishma_old',2,0,NULL,NULL,'X445',181,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('206','מתנפח 4 תחנות (X320)','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X320',182,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('207','מתנפח 4 תחנות (X339)','ללא קטגוריה',NULL,'0','alishma_old',2,0,NULL,NULL,'X339',183,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('208','מתנפח לייזר קווסט 8/8 שחור סגול','ללא קטגוריה',NULL,'0','alishma_old',2,0,NULL,NULL,'X464',184,'{"alishma_old": 1, "alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('209','השור הזועם','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X371',185,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('210','שור זועם','ללא קטגוריה',NULL,'0','alishma_old',2,0,NULL,NULL,'X789',186,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('211','שער כניסה קרקס - לקרמבו','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X389',187,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('212','מתנפח מגלשת מים מסוק לקרמבו','ללא קטגוריה',NULL,'0','alishma_old',2,0,NULL,NULL,'X401',188,'{"alishma_old": 2}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('213','מתנפח כדור שקוף','ללא קטגוריה',NULL,'0','alishma_old',2,0,NULL,NULL,'X408',189,'{"alishma_old": 1, "alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('214','מתנפח פלמנגו לקרמבו','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'Z491',190,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('215','ברווז מתנפח לקרמבו','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X490',191,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('216','מתנפח מגלשת מדוזות','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X402',192,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('217','כיסויים למפוחים','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X888',193,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('218','קסדות ראש','ללא קטגוריה',NULL,'0','alishma_old',100,0,NULL,NULL,'X441',194,'{"alishma_old": 100}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('219','מגלשת מים בסגנון לגו','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X-402L',195,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('220','מתנפח סופר טאנקר','ללא קטגוריה',NULL,'0','misrad',1,0,NULL,NULL,'X461',196,'{"misrad": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('221','מתנפח פרמידת כדורגל','ללא קטגוריה',NULL,'0','alishma_new',4,0,NULL,NULL,'X502',197,'{"alishma_new": 4}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('222','מערכת כפתורים IPS','ללא קטגוריה',NULL,'0','alishma_new',1,0,NULL,NULL,'IPS',198,'{"alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('223','שער כניסה סנטה','ללא קטגוריה',NULL,'0','alishma_new',1,0,NULL,NULL,'X504',199,'{"alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('224','דמות סנטה מתנפחת','ללא קטגוריה',NULL,'0','alishma_new',1,0,NULL,NULL,'X505',200,'{"alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('225','דמות עז מתנפחת','ללא קטגוריה',NULL,'0','alishma_new',1,0,NULL,NULL,'X506',201,'{"alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('226','מתנפח קפיצות משולב מגלשה טרקטור','ללא קטגוריה',NULL,'0','alishma_new',1,0,NULL,NULL,'KS-103C',202,'{"alishma_new": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('227','לא ידוע (X428)','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X428',203,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('228','לא ידוע (X473)','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X473',204,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('229','לא ידוע (X409)','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X409',205,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('230','לא ידוע (KS-108)','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'KS-108',206,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('231','לא ידוע (X392)','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X392',207,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id,name,category,dimensions,"costPrice",warehouse,quantity,"futureQty","futureDate",image,sku,display_order,warehouse_qty) VALUES ('232','לא ידוע (X331)','ללא קטגוריה',NULL,'0','alishma_old',1,0,NULL,NULL,'X331',208,'{"alishma_old": 1}') ON CONFLICT (id) DO NOTHING;

-- ── App Settings ─────────────────────────────────────────────
INSERT INTO app_settings (key,value) VALUES ('categories','[{"key":"all","label":"הכל"},{"key":"bounce","label":"מתנפחי קפיצות"},{"key":"challenge","label":"אתגרונים"},{"key":"waterslide","label":"מגלשות מים"},{"key":"gymboree","label":"מתחמי ג׳ימבורי"},{"key":"character","label":"מייצגים"},{"key":"pool","label":"בריכות"},{"key":"sport","label":"ספורט"},{"key":"carnival","label":"קרנבל וקליעה"},{"key":"arch","label":"שערי כניסה"},"ללא קטגוריה",{"key":"ללא קטגוריה","label":"ללא קטגוריה"}]') ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO app_settings (key,value) VALUES ('serverURL','"https://landmine-thumb-stegosaur.ngrok-free.dev"') ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value;
INSERT INTO app_settings (key,value) VALUES ('whatsappNumber','"972509933322"') ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value;

-- ── Contacts (8 rows) ───────────────────────────────────────
INSERT INTO contacts (id,name,phone,created_at) VALUES ('mogwk3fon2ncc1utmfb','תומר דר','0505748224','2026-04-27 07:55:30.145088+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO contacts (id,name,phone,created_at) VALUES ('mogwkbio9q3r10tz9d7','לירן','0509933322','2026-04-27 07:55:40.533182+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO contacts (id,name,phone,created_at) VALUES ('moh3iqtijneblx5mbm','לירן (עידנ''ס)','0524496848','2026-04-27 11:10:24.397433+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO contacts (id,name,phone,created_at) VALUES ('moibdkgum2f4jfr56zr','יוסי עציון','0546773195','2026-04-28 07:38:04.766966+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO contacts (id,name,phone,created_at) VALUES ('moienp9uqgruf35nfh','לוילנד','0525956081','2026-04-28 09:09:56.378979+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO contacts (id,name,phone,created_at) VALUES ('moinm1c8mg5nmyka9s9','ירדן סימנה','0523230744','2026-04-28 13:20:35.016049+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO contacts (id,name,phone,created_at) VALUES ('mojsdwt6i0exurwedab','הודיה אפ לנד','0539866606','2026-04-29 08:22:01.006156+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO contacts (id,name,phone,created_at) VALUES ('mok7tbg344y6opwqocb','גל לוסטיג','0504222888','2026-04-29 15:33:54.936175+00') ON CONFLICT (id) DO NOTHING;

-- RLS policies for authenticated role
DROP POLICY IF EXISTS products_select ON products;
CREATE POLICY products_select ON products FOR SELECT USING (true);
DROP POLICY IF EXISTS products_write ON products;
CREATE POLICY products_write ON products FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS settings_all ON app_settings;
CREATE POLICY settings_all ON app_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- End of backup